name: Run Job Search Automation

on:
  schedule:
    - cron: '0 8 * * 1-5'    # 8:00 UTC
    - cron: '0 11 * * 1-5'   # 11:00 UTC
    - cron: '0 14 * * 1-5'   # 14:00 UTC
    - cron: '0 17 * * 1-5'   # 17:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-job-search:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "ADZUNA_APP_ID=${{ secrets.ADZUNA_APP_ID }}" >> .env
          echo "ADZUNA_APP_KEY=${{ secrets.ADZUNA_APP_KEY }}" >> .env
          echo "SEARCH_TERMS=${{ secrets.SEARCH_TERMS || 'Tester' }}" >> .env
          echo "LOCATION=${{ secrets.LOCATION || 'Gdansk' }}" >> .env
          echo "DISTANCE=${{ secrets.DISTANCE || '50' }}" >> .env

      # Restore sent_jobs.txt from cache
      - name: Restore sent_jobs cache
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: sent_jobs.txt
          key: sent-jobs-${{ github.run_id }}
          restore-keys: |
            sent-jobs-

      # Create empty sent_jobs.txt if not found in cache
      - name: Create empty sent_jobs.txt if needed
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          echo "No cached sent_jobs.txt found. Creating empty file."
          touch sent_jobs.txt

      # Debug step to see file contents
      - name: Debug sent_jobs.txt
        run: |
          echo "sent_jobs.txt before running script:"
          cat sent_jobs.txt || echo "File is empty or does not exist"

      - name: Run job search script
        run: python main.py

      # Debug step to see updated file contents
      - name: Debug updated sent_jobs.txt
        run: |
          echo "sent_jobs.txt after running script:"
          cat sent_jobs.txt || echo "File is empty or does not exist"

      # Upload logs as artifact (still useful for debugging)
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: job-search-logs
          path: job_search.log
          retention-days: 7