name: Run Tests Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Codziennie o 08:00 UTC
  workflow_dispatch:  # Pozwala na ręczne uruchomienie

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Twoja wersja Pythona (3.12.3)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt  # Dla zależności produkcyjnych

      - name: Run tests
        run: |
          pytest tests/  # Uruchamia testy z folderu tests/
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
          SEARCH_TERMS: ${{ secrets.SEARCH_TERMS || 'Tester' }}
          LOCATION: ${{ secrets.LOCATION || 'Gdansk' }}
          DISTANCE: ${{ secrets.DISTANCE || '50' }}

      - name: Upload test logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: job_search.log  # Jeśli testy generują logi
          retention-days: 7